### ISSUE TITLE
ios build errors

### ISSUE THREAD

**Issue by DarthRamone** [TuneOSS/xamarin-plugin#2]
I've added this binding as submodule to my project, and it does'nt build. I had to remove 

```
 <Import Project="$(MSBuildExtensionsPath)\Xamarin\Xamarin.ObjcBinding.CSharp.targets" />
```

this line from csproj, to make it work

**Comment by harshal-hasoffers** [comment]
Thanks for reporting the issue and its solution. We will sure take a look.
